os:
  - linux

language: php

php:
  - '7.2'

before_script:
  - composer self-update
  - composer install --no-interaction
  - cp .env.travis .env
#  - pear install pear/PHP_CodeSniffer
  - phpenv rehash
  - php artisan key:generate
  - touch database/database.sqlite
  - php artisan migrate
  - nvm install 11.3.0
  - npm install npm@latest -g
  - npm install -g jshint
  - npm install

#before_install:
#  - mysql -e 'CREATE DATABASE sport_testing'
#
#services:
#  - mysql

cache:
  directories:
    - node_modules
    - vendor

script:
  - vendor/bin/phpunit --coverage-text
  - phpcs --ignore=app/Http/Controllers/Auth,app/Http/Controllers/Controller.php app/Http/Controllers
  - npm run production
  - jshint resources/js/*
